### ISSUE TITLE
Allman vs K&R Einrückungsstiel 

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/HiWi#11]
Einrückungsstiele vergleichen. 

Bitte Allman und K&R stil vergleichen.

Ergebnisse bitte ins Wiki

**Comment by KDen404** [comment]
https://wiki.cluuub.xyz/de/hiwi-recherchen/Einr%C3%BCckungsstile

**Comment by Teigler** [comment]
Sieht schon gut aus. 
könntest bitte noch untersuchen, ob es zur Bevorzugung einer der beiden Stile wissenschaftliche Fakten gibt? Bitte hier dann auch die Quellen archivieren.

**Comment by KDen404** [comment]
Die Quellen sind auf den entsprechenden Wiki Seiten.
Ich habe jetzt nochmal diese Woche 3 Stunden damit verbracht Datenbanken zu durchsuchen nach abhandlungen welche einen aufschluss darüber geben könnten welcher der beiden Stile zu bevorzugen ist.

Ich habe keine Abhandlung gefunden welche den Allman stil analysiert bzw diesen mit anderen Stilen wie z.B. GNU, BSD, Linux vergleicht.
In Beauty and Maintainability of Code wird der GNU stil als der am besten pflegbare code beschrieben. K&R ist aufgrund der präsentierten Daten der Abhandlung als zweitbester Stil in der Wartung zu betrachten (Allman wurde in der Abhandlung nicht erwähnt).

Es gibt anscheinend nicht viele Abhandlungen über Einrückungsstile.

**Comment by Teigler** [comment]
Super, Danke dir.
