### ISSUE TITLE
[WIP] Recherche: LTI-Schnittstelle Moodle

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/HiWi#12]
Moodle unterstützt die LTI-Schnittstelle für die Integration von Lerninhalten auf Learning Plattformen. Diese soll evtl. Anwendung in AdLer finden. Stelle dazu bitte eine breitgefächerte Übersicht der Funktionalitäten und Möglichkeiten zusammen, die diese Schnittstelle bietet. Es reichen oberflächliche Beschreibungen. 
Die Übersicht sollte am Ende dann auf unserem Wiki liegen.

Bei Rückfragen einfach per Mail melden: marius.kaczmarek@hs-kempten.de

**Comment by funsimator** [comment]
https://wiki.cluuub.xyz/de/hiwi-recherchen/new-page

Passt das so, oder soll es ausführlicher sein?

**Comment by DerKatsche** [comment]
https://wiki.cluuub.xyz/e/de/hiwi-recherchen/lti 
Ich hab den Link der Wikiseite mal angepasst, damit man auch sieht was dahinter steckt. Wir schauen uns das mal an und geben dir Bescheid, ob wir iwo noch Bedarf für mehr Recherche sehen
Außerdem, könntest du den Task auf In Progress schieben? Dann sieht man auf einen Blick wie grade der Stand ist

**Comment by philgei** [comment]
Perfekt :)

Das LTI scheine eine größere baustelle zu sein. Und wird das auch werden. Im moment konzentrieren wir uns dann auf die Moodle Webservices. Die sind bereits aufgesetzt und bekannt. 

Vielen Dank für die Recherche. Hat uns einiges geholfen
