### ISSUE TITLE
Dependency Injection (DI) Container

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/HiWi#13]
Recherche:

- Wie sinnvoll sind DI Container.
- Ab wann sind diese sinnvoll
- Ist es sinnvoller die Dependency Injection selbst zu implementieren? Oder ab wann?
@funsimator könntest du das wenn mögliche machen, da du ja schon die Recherche zu DI Containern gemacht hast.

**Comment by funsimator** [comment]
Kann ich machen!

**Comment by funsimator** [comment]
https://wiki.cluuub.xyz/e/de/Softwareentwicklung/di-container

Kapitel: Wann sind DI Container sinnvoll?

Ist dir das konkret genug oder hättest du das ganze gerne konkreter?

**Comment by Teigler** [comment]
Abgeschlossen
