### ISSUE TITLE
Einarbeitung und Tests in Citavi

### ISSUE THREAD

**Issue by paulabartel** [ProjektAdLer/HiWi#15]
- Istallieren von Citavi, falls noch nicht geschehen (https://www.citavi.com/de)
- Vertraut machen mit den zentralen Funktionen, ggf. hierzu Video-Tutorials ansehen
- Folgende Beispiele als Test einpflegen und mit Kategorien versehen.

1) Albers, Sönke; Klapper, Daniel; Udo Konradt; Walter, Achim; Wolf, Joachim (Hg.) (2011): Methodik der empirischen Forschung. 3. Aufl. Wiesbaden.

2) Dorsch Lexikon der Psychologie (2022): Avatar. Online verfügbar unter https://dorsch.hogrefe.com/stichwort/avatar, zuletzt aktualisiert am 08.02.2022.

3) Diefenbach, Sarah; Hassenzahl, Marc (Hg.) (2017): Psychologie in der nutzerzentrierten Produktgestaltung. Wiesbaden: Springer.

Ansprechpartnerin: Paula

**Comment by KaktusHexe** [comment]
Ist erledigt, ich hab dir eine Einladung zu dem Test geschickt, falls du drüber gucken möchtest.
