### ISSUE TITLE
Ein EA Projekt für Autorentool

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/HiWi#17]
Da wir beim Autorentool derzeit noch in vielen verschiedenen EA Projekten arbeiten wollen wir diese zu einem Zusammenlegen. 

- Ein EA Projekt erstellen. 
- Jeden aus dem Autorentool nach einen EA Projekten Fragen
- alle EA Projekte zu einem EA Projekt zusammenstellen.

**Comment by KDen404** [comment]
Ich bräuchte die e-mail Adresse von (github: MarvinHo64) ansonsten habe ich bereits eine e-mail an alle die einen commit für das autorentool verfasst haben geschickt. Falls noch jemand etwas in EA für das Autorentool designed hat, bitte ich darum mir die e-mail Adressen derjenigen mitzuteilen.
