### ISSUE TITLE
Grafik in PowerPoint übertragen

### ISSUE THREAD

**Issue by paulabartel** [ProjektAdLer/HiWi#21]
Bitte die Grafik unten in einer PowerPoint-Präsentation „nachbauen“, also alle Felder mit Pfeilen etc. nachbilden. Hier kannst du gern gestalterisch werden und das ansprechender gestalten als es hier der Fall ist. :-)

Ansprechparter: Paula!

[Adaptivität.png](https://images.zenhubusercontent.com/61bba22296df8a36f7ea1285/e1710976-a936-431e-95a7-10561fd8de34)

**Comment by fatih078** [comment]
Erledigt 👍 
[Kriterien Adaptivität Lernsysteme.pptx](https://github.com/ProjektAdLer/HiWi/files/8245454/Kriterien.Adaptivitat.Lernsysteme.pptx)

**Comment by paulabartel** [comment]
danke :-)
