### ISSUE TITLE
Anforderungen C# zum Wiki hinzufügen

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/HiWi#4]
Bitte für das unten mitgeführte Dokument eine neue Wiki-Seite in folgendem Verzeichnis erstellen: https://wiki.cluuub.xyz/Softwareentwicklung

Bitte die Wiki-Seite auch gleich schön layouten.

[Anforderungen C#.docx](https://github.com/ProjektAdLer/HiWi/files/7746840/Anforderungen.C.docx)

**Comment by Teigler** [comment]
Servus, versuche bitte nochmal dieses Issue hier in der Pipeline zu verschieben.

**Comment by KDen404** [comment]
![grafik](https://user-images.githubusercontent.com/40216282/148833220-91a48c9f-37dd-48a6-b455-57d0ee14c047.png)
geht leider immer noch nicht

**Comment by Teigler** [comment]
Ich geh mal davon aus, dass du sowohl drag And drop als auch über die Pipelineeinstellungen (Piplines) vom Issue das versucht hast? Wahrscheinlich ist es ein Zenhub Bug.

**Comment by KDen404** [comment]
also jetzt funktioniert das pipeline switchen
