### ISSUE TITLE
AMG Meetings zum Wiki hinzufügen

### ISSUE THREAD

**Issue by Teigler** [ProjektAdLer/HiWi#5]
Bitte für jede unten mitgeführte Dokument eine Wiki-Seite in folgendem Verzeichnis erstellen: https://wiki.cluuub.xyz/de/AMG/Meetings

Bitte die Wiki-Seiten auch gleich schön layouten.

[Meeting_01_12_21.docx](https://github.com/ProjektAdLer/HiWi/files/7746914/Meeting_01_12_21.docx)
[Meeting_08_12_21.docx](https://github.com/ProjektAdLer/HiWi/files/7746915/Meeting_08_12_21.docx)
[Meeting_15_12_21.docx](https://github.com/ProjektAdLer/HiWi/files/7746916/Meeting_15_12_21.docx)
[Meeting_24_11_21.docx](https://github.com/ProjektAdLer/HiWi/files/7746917/Meeting_24_11_21.docx)
[Meeting_Vorlage.docx](https://github.com/ProjektAdLer/HiWi/files/7746919/Meeting_Vorlage.docx)

Achtung: die Vorlage bitte allgemeiner halten

**Comment by KDen404** [comment]
die hier?: https://wiki.cluuub.xyz/de/AMG/Meetings/Vorlage

**Comment by Teigler** [comment]
super danke
