### ISSUE TITLE
AdLer Engine (2D3D) Meeting Protokolle zum Wiki hinzufügen

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/HiWi#9]
Bitte unten stehende Protokolle nach https://wiki.cluuub.xyz/de/AdLerEngine/Meetings übertragen.

Es wäre schön, wenn  die Protokolle der AdLer Engine gleich formatiert sind, wie die Meeting Protokolle von AMG.

Protokolle:
https://syncandshare.lrz.de/open/MlJxM2hCeFMzZ2VORkJHRXZQZGdV/Präsentationen%2C%20Protokolle%20und%20Dokumentationen/AdLer_2D3D_Protokolle.docx

**Comment by DerKatsche** [comment]
Hab den Tasks für dich mal in Progress geschoben. 
Außerdem als Nachtrag: Mir ist aufgefallen, dass es nice wäre, wenn bei den Adler Engine Meetings auch noch die Protokoll-Vorlage als Seite dabei wäre.

**Comment by KDen404** [comment]
Done
falls dass dann alles war würde ich das hier als solved betrachten
